-- Diagnostika savol banki (versiya 1) - 926 savol.
-- AVTOMATIK YARATILGAN: `python -m platforma.savol_yukla --sql`.
-- Manba: materiallar/diagnostika/CJM yangi.xlsx, EJM yangi.xlsx.
-- Qo'lda tahrirlanmaydi. Savol matni o'zgarsa - YANGI versiya bilan
-- yangi migratsiya fayli qo'shiladi (eski diagnostika foizi
-- o'zgarmasin).
INSERT INTO diag_savollar(tur, bosqich, blok, tartib, matn,
                          versiya, ixtiyoriy) VALUES
  ('cjm','Tanilish','INSTAGRAM',1,'Instagram sahifasi mavjudmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',2,'Instagram Business Accountmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',3,'Profil rasmi professional darajadami?',1,false),
  ('cjm','Tanilish','INSTAGRAM',4,'Logotip sifatli ishlab chiqilganmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',5,'Bio to‘liq yozilganmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',6,'Bio ichida asosiy xizmatlar ko‘rsatilganmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',7,'Telefon raqami joylashtirilganmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',8,'Telegram havolasi mavjudmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',9,'Veb-sayt havolasi mavjudmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',10,'Lokatsiya ko‘rsatilganmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',11,'Highlightlar mavjudmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',12,'Highlightlar yagona dizayndami?',1,false),
  ('cjm','Tanilish','INSTAGRAM',13,'Xizmatlar haqida Highlight bormi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',14,'Xodimlar jamoasi haqida Highlight bormi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',15,'Mijozlar fikrlari Highlighti mavjudmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',16,'Yutib olingan ishlar haqida Highlight bormi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',17,'Haftasiga kamida 3 ta post chiqadimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',18,'Haftasiga kamida 3 ta reels chiqadimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',19,'Kontent rejasi mavjudmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',20,'Senariylar bormi video uchun?',1,false),
  ('cjm','Tanilish','INSTAGRAM',21,'Media plan bormi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',22,'Kontent kalendari mavjudmi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',23,'Huquqiy maslahat videolari chiqariladimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',24,'Mijoz muammolari bo‘yicha kontentlar bormi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',25,'CTA (harakatga chaqirish) ishlatiladimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',26,'Storylar har kuni joylanadimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',27,'Reach ko‘rsatkichlari kuzatiladimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',28,'Engagement ko‘rsatkichlari kuzatiladimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',29,'Profilga kiruvchilar soni kuzatiladimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',30,'Leadlar soni hisoblanadimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',31,'Xodimlarning shaxsiy brendi yuritiladimi?',1,false),
  ('cjm','Tanilish','INSTAGRAM',32,'Instagram orqali oyiga mijozlar keladimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',1,'Telegram kanal mavjudmi?',1,false),
  ('cjm','Tanilish','TELEGRAM',2,'Kanal professional rasmiylashtirilganmi?',1,false),
  ('cjm','Tanilish','TELEGRAM',3,'Kanal tavsifi yozilganmi?',1,false),
  ('cjm','Tanilish','TELEGRAM',4,'Aloqa ma''lumotlari mavjudmi?',1,false),
  ('cjm','Tanilish','TELEGRAM',5,'Xizmatlar haqida ma''lumot berilganmi?',1,false),
  ('cjm','Tanilish','TELEGRAM',6,'Haftasiga kamida 3 ta post chiqadimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',7,'Yangiliklar joylanadimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',8,'Amaliyotlari tahlili beriladimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',9,'Video kontentlar joylanadimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',10,'PDF qo‘llanmalar ulashiladimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',11,'Obunachilar soni kuzatiladimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',12,'Post ko‘rishlar soni kuzatiladimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',13,'CTA ishlatiladimi?',1,false),
  ('cjm','Tanilish','TELEGRAM',14,'Telegram bot mavjudmi?',1,false),
  ('cjm','Tanilish','TELEGRAM',15,'Telegram orqali oyiga mijozlar keladimi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',1,'Meta Ads ishlatiladimi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',2,'Google Ads ishlatiladimi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',3,'Reklama byudjeti mavjudmi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',4,'CPL hisoblanadimi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',5,'CTR hisoblanadimi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',6,'Advokatlar OAVda chiqish qilganmi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',7,'Podkastlarda qatnashganmi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',8,'Intervyular mavjudmi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',9,'PR strategiyasi mavjudmi?',1,false),
  ('cjm','Tanilish','REKLAMA VA PR',10,'Brend tanilish KPIlari mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',1,'Rasmiy veb-sayt mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',2,'Mobil versiyasi ishlaydimi?',1,false),
  ('cjm','Tanilish','WEBSITE',3,'SSL sertifikati mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',4,'Bosh sahifa professional ko‘rinishdami?',1,false),
  ('cjm','Tanilish','WEBSITE',5,'Xizmatlar sahifasi mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',6,'Jamoalar sahifasi mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',7,'Jamoa haqida ma''lumot mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',8,'Portfolio mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',9,'Ishlari misollari mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',10,'Blog mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',11,'FAQ mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',12,'Aloqa formasi mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',13,'Telegram tugmasi mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',14,'Qo‘ng‘iroq tugmasi mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',15,'CTA mavjudmi?',1,false),
  ('cjm','Tanilish','WEBSITE',16,'SEO optimizatsiya qilinganmi?',1,false),
  ('cjm','Tanilish','WEBSITE',17,'Google Analytics ulanganmi?',1,false),
  ('cjm','Tanilish','WEBSITE',18,'Meta Pixel ulanganmi?',1,false),
  ('cjm','Tanilish','WEBSITE',19,'Sayt trafiklari o‘lchanadimi?',1,false),
  ('cjm','Tanilish','WEBSITE',20,'Sayt orqali oyiga mijozlar keladimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',1,'Google Maps kartasi mavjudmi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',2,'Lokatsiya to‘g‘ri ko‘rsatilganmi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',3,'Telefon raqami joylashtirilganmi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',4,'Ish vaqti ko‘rsatilganmi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',5,'Sayt havolasi mavjudmi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',6,'Ofis fotosuratlari joylashtirilganmi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',7,'Jamoa fotosuratlari mavjudmi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',8,'Google Maps orqali yangi mijozlar keladimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',9,'Mijozlar korxonani Google Maps orqali oson topadimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',10,'Maps orqali kelgan murojaatlar savdoga aylanadimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',11,'Reyting 4.5 dan yuqorimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',12,'Sharhlarga javob beriladimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',13,'Trafik kuzatiladimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',14,'Maps orqali qo‘ng‘iroqlar hisoblanadimi?',1,false),
  ('cjm','Tanilish','GOOGLE MAPS',15,'Maps orqali mijozlar keladimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',1,'YouTube kanal mavjudmi?',1,false),
  ('cjm','Tanilish','YOU TUBE',2,'Shorts videolar chiqariladimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',3,'Maslahat videolari mavjudmi?',1,false),
  ('cjm','Tanilish','YOU TUBE',4,'Intervyular joylanadimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',5,'Ishlari tahlili beriladimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',6,'Obunachilar soni kuzatiladimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',7,'Ko‘rishlar soni kuzatiladimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',8,'CTA ishlatiladimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',9,'SEO ishlatiladimi?',1,false),
  ('cjm','Tanilish','YOU TUBE',10,'YouTube orqali mijozlar keladimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',1,'Yozma otzivlar mavjudmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',2,'Otzivlar saytga joylashtirilganmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',3,'Otzivlar Instagramga joylashtirilganmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',4,'Google Reviews yig''iladimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',5,'Har oy yangi otziv olinadimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',6,'Korporativ mijozlar otzivlari mavjudmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',7,'Jismoniy shaxslar otzivlari mavjudmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',8,'Otzivlarda ism va familiya ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',9,'Otzivlar haqiqiy ekanligi tasdiqlanganmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',10,'Mijoz natijalari yozilganmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',11,'Otzivlar muntazam yangilanadimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',12,'Negativ otzivlar nazorat qilinadimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',13,'Negativ otzivlarga javob beriladimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',14,'Otziv yig''ish bo''yicha standart mavjudmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',15,'Otziv yig''ish uchun mas''ul xodim bormi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',16,'Otzivlar CRMga kiritiladimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',17,'Otzivlardan reklamada foydalaniladimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',18,'Eng kuchli otzivlar alohida ajratilganmi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',19,'Mijoz qoniqish darajasi o''lchanadimi?',1,false),
  ('cjm','Ishonch','OTZIVLAR',20,'Otzivlar sotuvga ta''siri tahlil qilinadimi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',1,'Video otzivlar mavjudmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',2,'Video otzivlar professional suratga olinganmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',3,'Video otzivlar Instagramda mavjudmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',4,'Video otzivlar saytda mavjudmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',5,'Video otzivlar YouTube’da mavjudmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',6,'Har oy yangi video otziv olinadimi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',7,'Korporativ mijoz video otzivlari bormi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',8,'Jismoniy shaxs video otzivlari bormi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',9,'Mijoz natijasi videoda ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',10,'Video otzivlarda ism-familiya aytilganmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',11,'Video otzivlardan reklamada foydalaniladimi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',12,'Video otzivlar montaj qilinganmi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',13,'Video otzivlar subtitr bilan chiqariladimi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',14,'Video otzivlar CTA bilan yakunlanadimi?',1,false),
  ('cjm','Ishonch','VIDEO OTZIVLAR',15,'Video otzivlar konversiyaga ta''siri o''lchanadimi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',1,'Portfolio mavjudmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',2,'Portfolio saytga joylashtirilganmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',3,'Portfolio PDF shaklida mavjudmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',4,'Korporativ mijozlar ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',5,'Jismoniy shaxslar ishlari mavjudmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',6,'Fuqarolik ishlari misollari bormi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',7,'Iqtisodiy ishlari misollari bormi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',8,'Xizmat masalalari bo''yicha ishlar bormi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',9,'Mehnat nizolari bo''yicha ishlar bormi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',10,'Muvaffaqiyatli yakunlangan ishlar ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',11,'Portfolio muntazam yangilanadimi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',12,'Portfolio vizual ko''rinishda tayyorlanganmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',13,'Har bir ish bo''yicha natija ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',14,'Mijoz roziligi olinganmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',15,'Portfolio sotuvda ishlatiladimi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',16,'Portfolio menejerlarda mavjudmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',17,'Portfolio taqdimotlarda ishlatiladimi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',18,'Portfolio reklamada ishlatiladimi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',19,'Portfolio bo''yicha KPI mavjudmi?',1,false),
  ('cjm','Ishonch','PORTFOLIO',20,'Portfolio orqali kelgan mijozlar hisoblanadimi?',1,false),
  ('cjm','Ishonch','CASE STUDY',1,'Case study mavjudmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',2,'Muammo aniq tasvirlanganmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',3,'Mijoz vaziyati yozilganmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',4,'Yechim ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',5,'Natija ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',6,'Moliyaviy natija ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',7,'Xizmat asosi ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',8,'Real hujjatlar mavjudmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',9,'Vizual materiallar mavjudmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',10,'Case study saytda mavjudmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',11,'Har oy yangi case study chiqariladimi?',1,false),
  ('cjm','Ishonch','CASE STUDY',12,'Korporativ case studylar bormi?',1,false),
  ('cjm','Ishonch','CASE STUDY',13,'Jismoniy shaxs case studylari bormi?',1,false),
  ('cjm','Ishonch','CASE STUDY',14,'Sotuvda ishlatiladimi?',1,false),
  ('cjm','Ishonch','CASE STUDY',15,'Reklamada ishlatiladimi?',1,false),
  ('cjm','Ishonch','CASE STUDY',16,'KPI mavjudmi?',1,false),
  ('cjm','Ishonch','CASE STUDY',17,'Konversiyaga ta''siri o''lchanadimi?',1,false),
  ('cjm','Ishonch','JAMOA',1,'Har bir xodim profili mavjudmi?',1,false),
  ('cjm','Ishonch','JAMOA',2,'Tajriba yillari ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','JAMOA',3,'Mutaxassisliklari yozilganmi?',1,false),
  ('cjm','Ishonch','JAMOA',4,'Professional fotosuratlari mavjudmi?',1,false),
  ('cjm','Ishonch','JAMOA',5,'LinkedIn profillari mavjudmi?',1,false),
  ('cjm','Ishonch','JAMOA',6,'Jamoa videolari mavjudmi?',1,false),
  ('cjm','Ishonch','JAMOA',7,'Tashkilot strukturasi ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','JAMOA',8,'Rahbar profili mavjudmi?',1,false),
  ('cjm','Ishonch','JAMOA',9,'Jamoa haqida postlar chiqariladimi?',1,false),
  ('cjm','Ishonch','JAMOA',10,'Jamoa haqida video chiqariladimi?',1,false),
  ('cjm','Ishonch','JAMOA',11,'Jamoa mukofotlari ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','JAMOA',12,'Ichki treninglar o''tkaziladimi?',1,false),
  ('cjm','Ishonch','JAMOA',13,'Ekspertlik darajasi ko''rsatilganmi?',1,false),
  ('cjm','Ishonch','JAMOA',14,'Jamoa KPIlari mavjudmi?',1,false),
  ('cjm','Ishonch','JAMOA',15,'Jamoa brendga ishlaydimi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',1,'Litsenziyalari mavjudmi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',2,'Sertifikatlar saytga joylashtirilganmi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',3,'Sertifikatlar Instagramga joylashtirilganmi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',4,'Sertifikatlar ofisda namoyish qilinganmi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',5,'Xalqaro sertifikatlar mavjudmi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',6,'Malaka oshirish hujjatlari mavjudmi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',7,'Har yili yangilanadimi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',8,'Sertifikatlar reklamada ishlatiladimi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',9,'Sertifikatlar sotuvda ishlatiladimi?',1,false),
  ('cjm','Ishonch','SERTIFIKATLAR',10,'Sertifikatlar ishonchni oshirish KPIlariga ta''siri o''lchanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',1,'Call operator skripti mavjudmi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',2,'Salomlashuv standarti mavjudmi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',3,'Kompaniya taqdimoti standartimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',4,'Mijoz ismi yozib olinadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',5,'Telefon raqami CRMga kiritiladimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',6,'Murojaat sababi aniqlanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',7,'Mijoz turi aniqlanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',8,'Yuridik yoki jismoniy shaxs aniqlanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',9,'Muammo kategoriyasi aniqlanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',10,'Xodim bilan bog''lash skripti mavjudmi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',11,'Qo''ng''iroq yozib olinadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',12,'Qo''ng''iroqlar tekshiriladimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',13,'KPI mavjudmi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',14,'O''rtacha javob berish vaqti o''lchanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',15,'Yo''qotilgan qo''ng''iroqlar hisoblanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',16,'Callback tizimi mavjudmi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',17,'Qo''ng''iroq sifati baholanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',18,'Mijozga follow-up qilinadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',19,'Lead CRMga o''tkaziladimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',20,'Lead manbasi belgilanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',21,'Telegramga o''tkazish jarayoni mavjudmi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',22,'WhatsAppga o''tkazish jarayoni mavjudmi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',23,'Konsultatsiya uchrashuvi belgilanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',24,'Mijoz ma''lumotlari saqlanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',25,'Kunlik hisobot yuritiladimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',26,'Haftalik hisobot yuritiladimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',27,'Oylik konversiya hisoblanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',28,'Mijoz qoniqishi o''lchanadimi?',1,false),
  ('cjm','Sotuv','CALL OPERATOR',29,'Operatorlar o''qitiladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',1,'Konsultatsiya skripti mavjudmi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',2,'Mijoz muammosi chuqur aniqlanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',3,'Savollar ro''yxati mavjudmi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',4,'Huquqiy tavakkalchilik tushuntiriladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',5,'Mijoz maqsadi aniqlanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',6,'Qaror qabul qiluvchi aniqlanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',7,'Budjet aniqlanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',8,'Muddatlar aniqlanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',9,'Muqobil variantlar tushuntiriladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',10,'Xizmat qiymati tushuntiriladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',11,'Firma afzalliklari tushuntiriladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',12,'Portfolio ko''rsatiladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',13,'Case study ko''rsatiladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',14,'Otzivlar ko''rsatiladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',15,'E''tirozlar bilan ishlanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',16,'Keyingi qadam belgilanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',17,'Tijorat taklifi yuboriladimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',18,'Follow-up belgilanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',19,'Konversiya hisoblanadimi?',1,false),
  ('cjm','Sotuv','KONSULTATSIYA',20,'Konsultatsiya sifati nazorat qilinadimi?',1,false),
  ('cjm','Sotuv','CRM',1,'CRM tizimi mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',2,'Barcha lidlar CRMga tushadimi?',1,false),
  ('cjm','Sotuv','CRM',3,'Lid manbalari belgilanadimi?',1,false),
  ('cjm','Sotuv','CRM',4,'Lid statuslari mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',5,'Pipeline mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',6,'Bitim bosqichlari mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',7,'Mas''ullar tayinlanadimi?',1,false),
  ('cjm','Sotuv','CRM',8,'Vazifalar qo''yiladimi?',1,false),
  ('cjm','Sotuv','CRM',9,'Reminder mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',10,'Follow-up avtomatlashtirilganmi?',1,false),
  ('cjm','Sotuv','CRM',11,'Yo''qotilgan lidlar hisoblanadimi?',1,false),
  ('cjm','Sotuv','CRM',12,'Yo''qotilgan sabablar yoziladimi?',1,false),
  ('cjm','Sotuv','CRM',13,'Lead response time o''lchanadimi?',1,false),
  ('cjm','Sotuv','CRM',14,'Dashboard mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',15,'Konversiya o''lchanadimi?',1,false),
  ('cjm','Sotuv','CRM',16,'Manager KPIlari mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',17,'CRM integratsiyalari mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',18,'Telegram integratsiyasi mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',19,'Telefoniya integratsiyasi mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',20,'Email integratsiyasi mavjudmi?',1,false),
  ('cjm','Sotuv','CRM',21,'Takroriy mijozlar ajratiladimi?',1,false),
  ('cjm','Sotuv','CRM',22,'Korporativ mijozlar segmentlanadimi?',1,false),
  ('cjm','Sotuv','CRM',23,'Jismoniy shaxslar segmentlanadimi?',1,false),
  ('cjm','Sotuv','CRM',24,'Hisobotlar avtomatik shakllanadimi?',1,false),
  ('cjm','Sotuv','CRM',25,'Oylik tahlil o''tkaziladimi?',1,false),
  ('cjm','Sotuv','CRM',26,'CRMdan foydalanish nazorat qilinadimi?',1,false),
  ('cjm','Sotuv','CRM',27,'Xodimlar CRM bo''yicha o''qitilganmi?',1,false),
  ('cjm','Sotuv','CRM',28,'CRM xavfsizligi ta''minlanganmi?',1,false),
  ('cjm','Sotuv','CRM',29,'Ma''lumotlar zaxiralanganmi?',1,false),
  ('cjm','Sotuv','CRM',30,'CRM samaradorligi baholanadimi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',1,'Call operator skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',2,'Telegram yozishma skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',3,'WhatsApp skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',4,'Konsultatsiya skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',5,'Ehtiyoj aniqlash skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',6,'Why-How-What ishlatiladimi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',7,'SPIN savollari mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',8,'E''tirozlarni qaytarish skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',9,'Narx e''tirozi skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',10,'Raqobatchi e''tirozi skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',11,'Vaqt yo''q e''tirozi skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',12,'O''ylab ko''raman e''tirozi skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',13,'Follow-up skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',14,'Takroriy qo''ng''iroq skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',15,'Referral so''rash skripti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',16,'Skriptlar hujjatlashtirilganmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',17,'Skriptlar yangilanadimi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',18,'Skriptlardan foydalanish nazorat qilinadimi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',19,'Skriptlar test qilinadimi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',20,'Skriptlar KPIga bog''langanmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',21,'Skript treninglari o''tkaziladimi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',22,'Eng yaxshi skriptlar ajratilganmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',23,'Audio namunalar mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',24,'Video namunalar mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',25,'Sotuv standarti mavjudmi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',26,'Mijoz segmentlariga mos skriptlar bormi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',27,'Korporativ mijoz skripti bormi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',28,'Jismoniy shaxs skripti bormi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',29,'VIP mijoz skripti bormi?',1,false),
  ('cjm','Sotuv','SKRIPTLAR',30,'Skript samaradorligi o''lchanadimi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',1,'Tijorat taklifi mavjudmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',2,'PPT shakli mavjudmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',3,'PDF shakli mavjudmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',4,'Xizmatlar aniq yozilganmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',5,'Narxlar ko''rsatilganmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',6,'Paketlar mavjudmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',7,'Afzalliklar ko''rsatilganmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',8,'Case study qo''shilganmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',9,'Otzivlar qo''shilganmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',10,'CTA mavjudmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',11,'Dizayni professionalmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',12,'Har bir xizmat uchun alohida taklif bormi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',13,'Taklif yuborish standarti mavjudmi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',14,'Taklif ochilishi kuzatiladimi?',1,false),
  ('cjm','Sotuv','TIJORAT TAKLIFI',15,'Taklif konversiyasi hisoblanadimi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',1,'Standart shartnoma mavjudmi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',2,'Korporativ mijozlar uchun shartnoma bormi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',3,'Jismoniy shaxslar uchun shartnoma bormi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',4,'Shartnoma tez tayyorlanadimi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',5,'Elektron imzo ishlatiladimi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',6,'Hujjatlar nazorati mavjudmi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',7,'To''lov shartlari aniqmi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',8,'Xavflar yozilganmi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',9,'Arxiv yuritiladimi?',1,false),
  ('cjm','Sotuv','SHARTNOMA',10,'Shartnoma KPIlari mavjudmi?',1,false),
  ('cjm','Sotuv','KPI',1,'Konversiya foizi hisoblanadimi?',1,false),
  ('cjm','Sotuv','KPI',2,'CPL hisoblanadimi?',1,false),
  ('cjm','Sotuv','KPI',3,'CAC hisoblanadimi?',1,false),
  ('cjm','Sotuv','KPI',4,'LTV hisoblanadimi?',1,false),
  ('cjm','Sotuv','KPI',5,'Har bir menejer KPIga ega emasmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',1,'Follow-up standarti mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',2,'Har bir mijoz bilan xizmat tugagandan keyin aloqa qilinadimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',3,'3 kunlik follow-up mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',4,'7 kunlik follow-up mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',5,'30 kunlik follow-up mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',6,'Follow-up CRM orqali nazorat qilinadimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',7,'Follow-up uchun mas''ul xodim mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',8,'Follow-up natijalari CRMga yoziladimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',9,'Follow-up konversiyasi o''lchanadimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',10,'Yo''qotilgan mijozlarga follow-up qilinadimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',11,'Reminder tizimi mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',12,'Shartnoma tugashidan oldin eslatma yuboriladimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',13,'Sud majlisi sanasi eslatiladimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',14,'Hujjat topshirish muddati eslatiladimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',15,'To''lov muddati eslatiladimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',16,'Telegram reminder mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',17,'SMS reminder mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',18,'Email reminder mavjudmi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',19,'Reminder samaradorligi o''lchanadimi?',1,false),
  ('cjm','Qayta sotuv','FOLLOW-UP',20,'Reminder avtomatlashtirilganmi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',1,'Email bazasi mavjudmi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',2,'Mijoz email manzillari yig''iladimi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',3,'Email marketing ishlatiladimi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',4,'Huquqiy yangiliklar yuboriladimi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',5,'Oylik newsletter mavjudmi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',6,'Email ochilish foizi o''lchanadimi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',7,'Email bosilish foizi o''lchanadimi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',8,'Segmentlangan email yuboriladimi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',9,'Korporativ mijozlarga alohida email yuboriladimi?',1,false),
  ('cjm','Qayta sotuv','EMAIL',10,'Email orqali qayta sotuvlar hisoblanadimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',1,'Telegram mijozlar bazasi mavjudmi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',2,'Telegram orqali huquqiy yangiliklar yuboriladimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',3,'Telegram orqali aksiyalar yuboriladimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',4,'Telegram orqali yangi xizmatlar tanishtiriladimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',5,'Telegram orqali follow-up qilinadimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',6,'Telegram bot mavjudmi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',7,'Telegram kampaniyalari o''lchanadimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',8,'Telegram orqali qayta murojaatlar hisoblanadimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',9,'Telegram orqali mijoz qoniqishi so''raladimi?',1,false),
  ('cjm','Qayta sotuv','TELEGRAM',10,'Telegram orqali qayta sotuv KPIlari mavjudmi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',1,'Cross-sell strategiyasi mavjudmi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',2,'Mijozlarga qo''shimcha xizmatlar taklif qilinadimi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',3,'Korporativ xizmatlar taklif qilinadimi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',4,'Soliq bo''yicha xizmatlar taklif qilinadimi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',5,'Mehnat huquqi bo''yicha xizmatlar taklif qilinadimi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',6,'Shartnoma ekspertizasi taklif qilinadimi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',7,'Cross-sell skripti mavjudmi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',8,'Cross-sell konversiyasi o''lchanadimi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',9,'Cross-sell daromadi hisoblanadimi?',1,false),
  ('cjm','Qayta sotuv','CROSS-SELL',10,'Cross-sell KPIlari mavjudmi?',1,false),
  ('cjm','Tavsiya','REFERRAL',1,'Referral dasturi mavjudmi?',1,false),
  ('cjm','Tavsiya','REFERRAL',2,'Mijozlarga tavsiya dasturi tushuntiriladimi?',1,false),
  ('cjm','Tavsiya','REFERRAL',3,'Tavsiya uchun bonus tizimi mavjudmi?',1,false),
  ('cjm','Tavsiya','REFERRAL',4,'Tavsiya bergan mijozlar hisoblanadimi?',1,false),
  ('cjm','Tavsiya','REFERRAL',5,'Tavsiya orqali kelgan mijozlar alohida belgilanadimi?',1,false),
  ('cjm','Tavsiya','REFERRAL',6,'Referral konversiyasi hisoblanadimi?',1,false),
  ('cjm','Tavsiya','REFERRAL',7,'Referral orqali tushgan daromad hisoblanadimi?',1,false),
  ('cjm','Tavsiya','REFERRAL',8,'Referral bo''yicha KPI mavjudmi?',1,false),
  ('cjm','Tavsiya','REFERRAL',9,'Referral kampaniyalari o''tkaziladimi?',1,false),
  ('cjm','Tavsiya','REFERRAL',10,'Referral strategiyasi yozilganmi?',1,false),
  ('cjm','Tavsiya','NPS',1,'NPS (Net Promoter Score) o''lchanadimi?',1,false),
  ('cjm','Tavsiya','NPS',2,'Mijozlarga NPS so''rovnomasi yuboriladimi?',1,false),
  ('cjm','Tavsiya','NPS',3,'Xizmat tugagandan keyin NPS olinadimi?',1,false),
  ('cjm','Tavsiya','NPS',4,'NPS natijalari CRMga kiritiladimi?',1,false),
  ('cjm','Tavsiya','NPS',5,'NPS bo''yicha hisobot yuritiladimi?',1,false),
  ('cjm','Tavsiya','NPS',6,'NPS pasayish sabablari tahlil qilinadimi?',1,false),
  ('cjm','Tavsiya','NPS',7,'NPS oshirish rejasi mavjudmi?',1,false),
  ('cjm','Tavsiya','NPS',8,'NPS bo''yicha mas''ul xodim mavjudmi?',1,false),
  ('cjm','Tavsiya','NPS',9,'Har oy NPS ko''rsatkichlari ko''rib chiqiladimi?',1,false),
  ('cjm','Tavsiya','NPS',10,'NPS KPI mavjudmi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',1,'Google Review yig''ish tizimi mavjudmi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',2,'Har bir mijozdan sharh so''raladimi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',3,'Sharh qoldirish bo''yicha yo''riqnoma mavjudmi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',4,'Google Review linki yuboriladimi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',5,'Oyiga yangi sharhlar olinadimi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',6,'Sharhlarga javob beriladimi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',7,'Salbiy sharhlarga javob beriladimi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',8,'Google reytingi kuzatiladimi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',9,'Google Review KPI mavjudmi?',1,false),
  ('cjm','Tavsiya','GOOGLE REVIEW',10,'Google Review sotuvga ta''siri o''lchanadimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',1,'Video review yig''ish tizimi mavjudmi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',2,'Har oy video review olinadimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',3,'Korporativ mijozlardan video review olinadimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',4,'Jismoniy shaxslardan video review olinadimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',5,'Video review Instagramga joylanadimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',6,'Video review saytga joylanadimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',7,'Video review reklamada ishlatiladimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',8,'Video review konversiyasi o''lchanadimi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',9,'Video review uchun skript mavjudmi?',1,false),
  ('cjm','Tavsiya','VIDEO REVIEW',10,'Video review KPI mavjudmi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',1,'Hamkorlik dasturi mavjudmi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',2,'Hamkorlar bazasi yuritiladimi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',3,'Buxgalteriya kompaniyalari bilan hamkorlik bormi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',4,'Konsalting kompaniyalari bilan hamkorlik bormi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',5,'Sug''urta kompaniyalari bilan hamkorlik bormi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',6,'HR kompaniyalari bilan hamkorlik bormi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',7,'Hamkorlardan mijozlar keladimi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',8,'Hamkorlik orqali kelgan mijozlar hisoblanadimi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',9,'Hamkorlik daromadi hisoblanadimi?',1,false),
  ('cjm','Tavsiya','HAMKORLIK',10,'Hamkorlik KPI mavjudmi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',1,'Chat Place tizimi joriy qilinganmi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',2,'Saytga Chat Place integratsiya qilinganmi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',3,'Telegram bilan integratsiya mavjudmi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',4,'Instagram Direct bilan integratsiya mavjudmi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',5,'Barcha murojaatlar bitta oynada yig‘iladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',6,'Mijozlarga avtomatik salomlashish xabari yuboriladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',7,'Ish vaqtidan tashqarida avtomatik javob ishlaydimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',8,'FAQ (tez-tez beriladigan savollar) uchun avtomatik javoblar sozlanganmi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',9,'Operatorlar o‘rtasida chatlar taqsimlanadimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',10,'Chatlar mas''ul xodimlarga biriktiriladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',11,'Murojaatlarga javob berish vaqti o‘lchanadimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',12,'Javobsiz qolgan chatlar nazorat qilinadimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',13,'Chat orqali kelgan lidlar CRMga uzatiladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',14,'Chat natijalari bo‘yicha hisobot shakllantiriladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','CHATPLACE',15,'Operatorlarning ishlashi monitoring qilinadimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',1,'Kompaniyada Zowy AI joriy qilinganmi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',2,'Zowy 24/7 ishlaydimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',3,'Zowy mijozlarning tez-tez beriladigan savollariga javob bera oladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',4,'Zowy operatorga murojaatni avtomatik yo‘naltira oladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',5,'Zowy lidlarni yig‘a oladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',6,'Zowy CRM bilan integratsiya qilinganmi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',7,'Zowy sayt bilan integratsiya qilinganmi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',8,'Zowy bir nechta tilda ishlay oladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',9,'Zowy javoblari kompaniya bilim bazasi asosida ishlaydimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',10,'AI javoblari muntazam yangilanadimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',11,'AI mijoz ma''lumotlarini xavfsiz saqlaydimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',12,'AI orqali hisobotlar olinadimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',13,'AI noto‘g‘ri javoblarini tahlil qilish jarayoni mavjudmi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',14,'AI orqali operatorlar yuklamasi kamaytirilganmi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',15,'AI konversiyani oshirish uchun ishlatiladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',16,'AI yangi mijozlarni saralash (lead qualification) vazifasini bajara oladimi?',1,false),
  ('cjm','Raqamli muloqot va AI','ZOWY AI',17,'AI biznes jarayonlariga real qiymat qo‘shayotganligi muntazam baholanadimi?',1,false),
  ('cjm','Muhit','Tashqi reklama',1,'Tashqi reklama osongina ko‘rinadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',2,'Tashqi reklama mijoz e’tiborini tortadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',3,'Tashqi reklama brend uslubiga mosmi?',1,true),
  ('cjm','Muhit','Tashqi reklama',4,'Tashqi reklamada kompaniya haqida asosiy ma’lumotlar aniq ko‘rsatilganmi?',1,true),
  ('cjm','Muhit','Tashqi reklama',5,'Tashqi reklama orqali bog‘lanish usullari aniq ko‘rsatilganmi?',1,true),
  ('cjm','Muhit','Tashqi reklama',6,'Tashqi reklama mijozni keyingi bosqichga o‘tishga undaydimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',7,'Tashqi reklama toza va yaxshi holatda saqlanadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',8,'Tashqi reklama muntazam nazorat qilinadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',9,'Tashqi reklama bo‘yicha yozma standart bormi?',1,true),
  ('cjm','Muhit','Tashqi reklama',10,'Tashqi reklama belgilangan standartlarga muvofiq joylashtirilganmi?',1,true),
  ('cjm','Muhit','Tashqi reklama',11,'Tashqi reklama raqobatchilar fonida ajralib turadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',12,'Tashqi reklama mijozda ishonch uyg‘otadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',13,'Tashqi reklama samaradorligi muntazam tahlil qilinadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',14,'Tashqi reklama bo‘yicha KPI yoki samaradorlik ko‘rsatkichlari belgilanganmi?',1,true),
  ('cjm','Muhit','Tashqi reklama',15,'Tashqi reklama bo‘yicha mijoz fikrlari yig‘iladimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',16,'Tashqi reklama bilan bog‘liq kamchiliklar qayd etilib bartaraf etiladimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',17,'Tashqi reklama yangi mijozlarni jalb qilayotganligi tahlil qilinadimi?',1,true),
  ('cjm','Muhit','Tashqi reklama',18,'Tashqi reklamani yaxshilash bo‘yicha muntazam reja ishlab chiqiladimi?',1,true),
  ('cjm','Muhit','Fasad',1,'Fasad osongina ko‘rinadimi?',1,true),
  ('cjm','Muhit','Fasad',2,'Fasad toza va ozodami?',1,true),
  ('cjm','Muhit','Fasad',3,'Fasad yaxshi saqlanadimi?',1,true),
  ('cjm','Muhit','Fasad',4,'Fasad brend uslubiga mosmi?',1,true),
  ('cjm','Muhit','Fasad',5,'Fasad zamonaviy va jozibali ko‘rinishga egami?',1,true),
  ('cjm','Muhit','Fasad',6,'Fasad mijozda ishonch uyg‘otadimi?',1,true),
  ('cjm','Muhit','Fasad',7,'Fasad raqobatchilardan ajralib turadimi?',1,true),
  ('cjm','Muhit','Fasad',8,'Fasaddagi nom va logotip aniq ko‘rinadimi?',1,true),
  ('cjm','Muhit','Fasad',9,'Fasaddagi yozuvlar o‘qishga qulaymi?',1,true),
  ('cjm','Muhit','Fasad',10,'Fasad kechki vaqtda ham yaxshi ko‘rinadimi?',1,true),
  ('cjm','Muhit','Fasad',11,'Fasad muntazam nazorat qilinadimi?',1,true),
  ('cjm','Muhit','Fasad',12,'Fasad bo‘yicha standart bormi?',1,true),
  ('cjm','Muhit','Fasad',13,'Fasad standartlarga muvofiq saqlanadimi?',1,true),
  ('cjm','Muhit','Fasad',14,'Fasad bo‘yicha sifat nazorati bormi?',1,true),
  ('cjm','Muhit','Fasad',15,'Fasad bo‘yicha KPI belgilanganmi?',1,true),
  ('cjm','Muhit','Fasad',16,'Fasad bo‘yicha mijoz fikri yig‘iladimi?',1,true),
  ('cjm','Muhit','Fasad',17,'Fasad bilan bog‘liq muammolar qayd etiladimi?',1,true),
  ('cjm','Muhit','Fasad',18,'Fasad samaradorligi tahlil qilinadimi?',1,true),
  ('cjm','Muhit','Fasad',19,'Fasadni yaxshilash rejasi bormi?',1,true),
  ('cjm','Muhit','Avtoturargoh',1,'Avtoturargoh bormi?',1,true),
  ('cjm','Muhit','Avtoturargoh',2,'Avtoturargohni topish osonmi?',1,true),
  ('cjm','Muhit','Avtoturargoh',3,'Avtoturargoh mijoz uchun qulaymi?',1,true),
  ('cjm','Muhit','Avtoturargoh',4,'Avtoturargoh yetarli sig‘imga egami?',1,true),
  ('cjm','Muhit','Avtoturargoh',5,'Avtoturargoh toza va ozodami?',1,true),
  ('cjm','Muhit','Avtoturargoh',6,'Avtoturargoh xavfsizmi?',1,true),
  ('cjm','Muhit','Avtoturargoh',7,'Avtoturargohga kirish va chiqish qulaymi?',1,true),
  ('cjm','Muhit','Avtoturargoh',8,'Avtoturargoh nogironligi bo‘lgan shaxslar uchun moslashtirilganmi?',1,true),
  ('cjm','Muhit','Avtoturargoh',9,'Avtoturargohda yo‘naltiruvchi belgilar yetarlimi?',1,true),
  ('cjm','Muhit','Avtoturargoh',10,'Avtoturargoh muntazam nazorat qilinadimi?',1,true),
  ('cjm','Muhit','Avtoturargoh',11,'Avtoturargoh yaxshi saqlanadimi?',1,true),
  ('cjm','Muhit','Avtoturargoh',12,'Avtoturargoh bo‘yicha standart bormi?',1,true),
  ('cjm','Muhit','Avtoturargoh',13,'Avtoturargoh standartlarga muvofiq saqlanadimi?',1,true),
  ('cjm','Muhit','Avtoturargoh',14,'Avtoturargoh bo‘yicha sifat nazorati bormi?',1,true),
  ('cjm','Muhit','Avtoturargoh',15,'Avtoturargoh bo‘yicha KPI belgilanganmi?',1,true),
  ('cjm','Muhit','Avtoturargoh',16,'Avtoturargoh bo‘yicha mijoz fikri yig‘iladimi?',1,true),
  ('cjm','Muhit','Avtoturargoh',17,'Avtoturargoh bilan bog‘liq muammolar qayd etiladimi?',1,true),
  ('cjm','Muhit','Avtoturargoh',18,'Avtoturargoh samaradorligi tahlil qilinadimi?',1,true),
  ('cjm','Muhit','Avtoturargoh',19,'Avtoturargohni yaxshilash rejasi bormi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',1,'Kirish qismi mijoz uchun qulaymi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',2,'Kirish qismi toza va ozodami?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',3,'Kirish qismi yorug‘ va shinammi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',4,'Kirish qismi xavfsizmi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',5,'Kirish qismi brend uslubiga mosmi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',6,'Kirish qismi mijozda ijobiy birinchi taassurot uyg‘otadimi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',7,'Kirish qismi nogironligi bo‘lgan shaxslar uchun qulaymi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',8,'Kirish qismi tartibli saqlanadimi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',9,'Kirish qismi muntazam nazorat qilinadimi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',10,'Kirish qismi bo‘yicha standart bormi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',11,'Kirish qismi standartlarga muvofiq saqlanadimi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',12,'Kirish qismi bo‘yicha sifat nazorati bormi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',13,'Kirish qismi bo‘yicha KPI belgilanganmi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',14,'Kirish qismi bo‘yicha mijoz fikri yig‘iladimi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',15,'Kirish qismi bilan bog‘liq muammolar qayd etiladimi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',16,'Kirish qismi samaradorligi tahlil qilinadimi?',1,true),
  ('cjm','Muhit','Kirish qismi (Entrance, hall)',17,'Kirish qismini yaxshilash rejasi bormi?',1,true),
  ('cjm','Muhit','Navigatsiya',1,'Navigatsiya tushunarlimi?',1,true),
  ('cjm','Muhit','Navigatsiya',2,'Navigatsiya belgilari aniq ko‘rinadimi?',1,true),
  ('cjm','Muhit','Navigatsiya',3,'Navigatsiya kerakli joyni tez topishga yordam beradimi?',1,true),
  ('cjm','Muhit','Navigatsiya',4,'Navigatsiya barcha asosiy yo‘nalishlarni qamrab olganmi?',1,true),
  ('cjm','Muhit','Navigatsiya',5,'Navigatsiya brend uslubiga mosmi?',1,true),
  ('cjm','Muhit','Navigatsiya',6,'Navigatsiya mijozda ishonch uyg‘otadimi?',1,true),
  ('cjm','Muhit','Navigatsiya',7,'Navigatsiya nogironligi bo‘lgan shaxslar uchun qulaymi?',1,true),
  ('cjm','Muhit','Navigatsiya',8,'Navigatsiya toza va yaxshi saqlanadimi?',1,true),
  ('cjm','Muhit','Navigatsiya',9,'Navigatsiya muntazam nazorat qilinadimi?',1,true),
  ('cjm','Muhit','Navigatsiya',10,'Navigatsiya bo‘yicha standart bormi?',1,true),
  ('cjm','Muhit','Navigatsiya',11,'Navigatsiya standartlarga muvofiq tashkil etilganmi?',1,true),
  ('cjm','Muhit','Navigatsiya',12,'Navigatsiya bo‘yicha sifat nazorati bormi?',1,true),
  ('cjm','Muhit','Navigatsiya',13,'Navigatsiya bo‘yicha KPI belgilanganmi?',1,true),
  ('cjm','Muhit','Navigatsiya',14,'Navigatsiya bo‘yicha mijoz fikri yig‘iladimi?',1,true),
  ('cjm','Muhit','Navigatsiya',15,'Navigatsiya bilan bog‘liq muammolar qayd etiladimi?',1,true),
  ('cjm','Muhit','Navigatsiya',16,'Navigatsiya samaradorligi tahlil qilinadimi?',1,true),
  ('cjm','Muhit','Navigatsiya',17,'Navigatsiyani yaxshilash rejasi bormi?',1,true),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',1,'Vakansiyada kompaniyaning afzalliklari yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',2,'Har bir lavozim uchun alohida vakansiya tayyorlanadimi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',3,'Ish vazifalari aniq yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',4,'Xodimdan nima kutilishi yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',5,'Ish vaqti ko‘rsatilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',6,'Ish joyi manzili ko‘rsatilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',7,'Maosh yoki maosh diapazoni ko‘rsatilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',8,'Sinov muddati haqida ma’lumot berilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',9,'Xodim kimga bo‘ysunishi yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',10,'O‘sish imkoniyatlari ko‘rsatilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',11,'Ish formati ko‘rsatilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',12,'Kerakli ish tajribasi yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',13,'Kerakli bilim va ko‘nikmalar yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',14,'Kerakli shaxsiy fazilatlar yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',15,'Murojaat qilish tartibi yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',16,'Vakansiya matni imlo xatolarisiz yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',17,'Vakansiyalar bir xil dizaynda tayyorlanadimi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',18,'Vakansiyalar Instagramda joylanadimi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',19,'Vakansiyalar Telegramda joylanadimi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',20,'Nomzod qaysi kanaldan kelgani hisobga olinadimi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',21,'Kompaniya beradigan sharoitlar yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',22,'Tanlov bosqichlari yozilganmi?',1,false),
  ('ejm','Tanilish','Ish beruvchi brendi va vakansiya',23,'Kompaniyaning asosiy faoliyat yo‘nalishlari ko‘rsatilganmi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',1,'Ish saytlari orqali nomzod topiladimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',2,'Telegram orqali nomzod topiladimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',3,'Instagram orqali nomzod topiladimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',4,'Tavsiyalar orqali nomzod topiladimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',5,'Eski nomzodlar bazasidan foydalaniladimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',6,'Har bir jalb qilish kanali bo’yicha konversiya ko’rsatkichlari kuzatiladimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',7,'Nomzod jalb qilish xarajati hisoblanadimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',8,'Eng samarali nomzod jalb qilish kanali aniqlanadimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',9,'Qaysi lavozimlarni to‘ldirish qiyinligi tahlil qilinadimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',10,'Nomzod jalb qilish bo‘yicha oylik hisobot tayyorlanadimi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',11,'Nomzod jalb qilish uchun mas’ul xodim belgilanganmi?',1,false),
  ('ejm','Tanilish','Nomzodlarni jalb qilish kanallari',12,'Nomzod jalb qilish bo‘yicha yillik reja bormi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',1,'Har bir lavozim uchun alohida vakansiya profili bormi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',2,'Nomzodga kompaniya haqida ma’lumot beriladimi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',3,'Nomzodga ish vazifalari va ish hajmi tushuntiriladimi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',4,'Nomzodga sinov topshirig‘i yoki amaliy sinov haqida oldindan aytiladimi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',5,'Nomzodga ish jarayonlari va standartlari tushuntiriladimi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',6,'Nomzodga ichki treninglar haqida ma’lumot beriladimi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',7,'Nomzodga KPI tizimi tushuntiriladimi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',8,'Nomzod bevosita rahbari bilan tanishtiriladimi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',9,'Jamoa haqida tanishtiruvchi kontentlar bormi?',1,false),
  ('ejm','Tanilish','Boʻlimlar tanilishi',10,'Nomzodlar alohida bazada yuritiladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',1,'Nomzod bilan birinchi aloqa qilish tartibi bormi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',2,'Birinchi qo‘ng‘iroq uchun savollar ro‘yxati bormi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',3,'Nomzodning ish tajribasi tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',4,'Nomzodning oldingi ishidan ketish sababi aniqlanadimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',5,'Nomzod qachondan ish boshlay olishi aniqlanadimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',6,'Nomzodning maosh kutuvi so‘raladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',7,'Nomzodning ish jadvaliga mosligi tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',8,'Nomzodning ish joyiga yetib kelish imkoniyati tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',9,'Nomzodning ishga motivatsiyasi aniqlanadimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',10,'Nomzodning kuchli va zaif tomonlari qayd etiladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',11,'Dastlabki suhbat natijasi yozib boriladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',12,'Saralashdan o‘tmagan nomzodlarga javob beriladimi?',1,false),
  ('ejm','Saralash va ishonch','Dastlabki saralash',13,'Dastlabki saralash natijalari tahlil qilinadimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',1,'Har bir lavozim uchun suhbat savollari tayyorlanganmi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',2,'Suhbatda ish vazifalari tushuntiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',3,'Suhbatda KPIlar tushuntiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',4,'Suhbatda sinov muddati shartlari tushuntiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',5,'Suhbatda jamoa va rahbar haqida ma’lumot beriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',6,'Nomzodning kompaniya qadriyatlariga mosligi tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',7,'Suhbatda vaziyatli savollar beriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',8,'Nomzodning oldingi ish natijalari so‘raladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',9,'Intizom va vaqtni boshqarish bo‘yicha savollar beriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',10,'Muammoli vaziyatlarda qanday yo‘l tutishi tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',11,'Suhbat natijalari yagona baholash shaklida rasmiylashtiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',12,'Ishga qabul qilish qarori uchun mas’ul shaxs aniqmi?',1,false),
  ('ejm','Saralash va ishonch','Suhbat jarayoni',13,'Suhbat sifati muntazam nazorat qilinadimi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',1,'Har bir lavozim uchun sinov topshirig‘i bormi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',2,'Sinov topshirig‘ini baholash mezonlari bormi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',3,'Sinov topshirig‘ini topshirish muddati aniqmi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',4,'Sinov topshirig‘i oldindan tushuntiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',5,'Nomzodga sinov topshirig‘i bo‘yicha fikr beriladimi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',6,'Sinov topshirig‘idan o‘tish ko‘rsatkichi hisoblanadimi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',7,'Qaysi topshiriqlarda nomzodlar ko‘proq qiyinchilikka duch kelayotgani tahlil qilinadimi?',1,false),
  ('ejm','Saralash va ishonch','Sinov topshiriq va baholash',8,'Sinov topshirig‘i muntazam yangilanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',1,'Amaliy sinov majburiymi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',2,'Amaliy sinov vazifasi va formati oldindan beriladimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',3,'Amaliy sinovni baholash mezonlari bormi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',4,'Amaliy sinovni rahbar yoki mas’ul xodim baholaydimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',5,'Nomzodning kasbiy bilimlari tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',6,'Nomzodning ishni tashkil qilish usuli baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',7,'Nomzodning tushuntirish va fikrni yetkazish usuli baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',8,'Nomzodning muloqot ko‘nikmalari baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',9,'Nomzodning mijoz yoki hamkor bilan muloqot qilish ko‘nikmasi baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',10,'Nomzodning ishni rejalashtirish ko‘nikmasi tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',11,'Nomzodning topshiriqlarni bajarish va nazorat qilish usuli baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',12,'Nomzodning intizomga rioya qilishi baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',13,'Nomzodning kompaniya standartlarini tushunishi tekshiriladimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',14,'Amaliy sinovdan keyin nomzodga fikr-mulohaza beriladimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',15,'Amaliy sinov natijalari alohida saqlanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',16,'Nomzodning vaqtni boshqarish ko‘nikmasi baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',17,'Nomzodning savollarga javob berish usuli baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',18,'Nomzodning ish qurollari yoki dasturlardan foydalanish ko‘nikmasi baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',19,'Nomzodning topshiriqni bajarish sifati baholanadimi?',1,false),
  ('ejm','Saralash va ishonch','Boʻlimlar saralashi',20,'Nomzodning ish davomida e’tiborni ushlab turishi va tashabbuskorligi baholanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',1,'Ish taklifini yuborish tartibi bormi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',2,'Ishga chiqishdan oldin kerakli hujjatlar ro‘yxati yuboriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',3,'Birinchi ish kuni rejasi oldindan yuboriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',4,'Xodimni kim kutib olishi oldindan aytiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',5,'Xodim uchun ish joyi va barcha zarur resurslar oldindan tayyorlanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',6,'Login va parollar oldindan tayyorlanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',7,'Xodim ish uchun kerakli platforma va guruhlarga oldindan qo‘shiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',8,'Lavozim yo‘riqnomasi oldindan yuboriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',9,'Ichki qoidalar oldindan yuboriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',10,'Sinov muddati maqsadlari oldindan tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',11,'Birinchi ish kunidan oldin xush kelibsiz xabari yuboriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',12,'Ishga chiqishdan oldin xodim bilan bog‘laniladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Pre-boarding',13,'Ishga chiqmagan nomzodlarning sababi qayd etiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',1,'Birinchi ish kuni uchun checklist bormi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',2,'Xodimga kompaniya tarixi tanishtiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',3,'Xodimga kompaniya maqsadlari tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',4,'Xodimga kompaniya qadriyatlari tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',5,'Xodimga kompaniya tuzilmasi tanishtiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',6,'Xodim jamoa bilan tanishtiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',7,'Xodimga ish joyi va bo‘limlar ko‘rsatiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',8,'Xodimga ish vaqti va ichki qoidalar tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',9,'Rahbar bilan birinchi uchrashuv o‘tkaziladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Birinchi kun',10,'Birinchi kun oxirida xodimning fikri olinadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',1,'Yangi xodim uchun 7-14 kunlik onboarding rejasi bormi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',2,'Yangi xodim uchun 30 kunlik moslashuv rejasi bormi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',3,'Yangi xodimning moslashuvi muntazam kuzatiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',4,'Har hafta yangi xodimning natijalari ko‘rib chiqiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',5,'Yangi xodimga ish uchun kerakli o‘quv materiallari beriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',6,'Yangi xodimga ichki reglament va jarayonlar tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',7,'Yangi xodimga hisobot topshirish tartibi o‘rgatiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',8,'Moslashuv davridagi muammolar va xatolar ustida ishlanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','30 kunlik moslashtirish',9,'30 kun yakunida yangi xodim baholanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',1,'Har bir lavozim uchun alohida onboarding rejasi bormi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',2,'Yangi xodim ishni bajarish uchun zarur barcha bilim, standart va tizimlarga o’rgatiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',3,'Yangi xodimga baholash mezonlari va KPIlar tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',4,'Yangi xodimga ish jarayonlari va ichki tartib-qoidalar tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',5,'Yangi xodim tajribali xodimning ish jarayonini kuzatadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',6,'Yangi xodimga mentor biriktiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',7,'Yangi xodimning ishi rahbar yoki mas’ul xodim tomonidan kuzatiladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',8,'Birinchi oy ichida yangi xodimga muntazam fikr-mulohaza beriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',9,'Birinchi oy yakunida yangi xodimning natijalari baholanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',10,'Sinov muddati yakunida yakuniy baholash o‘tkaziladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',11,'Onboarding jarayoni sifati o‘lchanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',12,'Yangi xodim ish jarayonlarini amalda bajarib ko‘rsatadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',13,'Yangi xodimning ish natijalari kuzatuv varaqasi yoki checklist orqali baholanadimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',14,'Ichki intizom qoidalari alohida tushuntiriladimi?',1,false),
  ('ejm','Ishga qabul va moslashtirish','Bo‘limlar moslashtirishi',15,'Yangi xodimning mijoz yoki hamkor bilan birinchi muloqoti nazorat qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',1,'Har bir xodim uchun KPI belgilanganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',2,'KPIlar xodimga tushuntirilganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',3,'KPIlar muntazam kuzatilib tahlil qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',4,'Har bir xodim bilan muntazam yakka suhbat o‘tkaziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',5,'Rahbarlar muntazam fikr-mulohaza beradimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',6,'Vazifalar yozma ravishda beriladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',7,'Vazifalar bajarilishi nazorat qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',8,'Vazifalarning ustuvorligi belgilanadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',9,'Muammolarni tezkor hal qilish uchun aloqa kanali bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',10,'Xodimning ish yuklamasi nazorat qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',11,'Natijasi past xodim uchun rivojlanish rejasi tuziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',12,'Rahbarlar ish sifati baholanadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',13,'Bo‘lim natijalari muntazam ko‘rib chiqiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boshqaruv va nazorat',14,'Ichki hisobotlar muntazam yuritiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',1,'Motivatsiya tizimi yozilganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',2,'Jarima qo‘llash tartibi yozilganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',3,'Xodimlarni rag‘batlantirish tizimi bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',4,'Eng yaxshi xodimni tanlash mezonlari belgilanganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',5,'Yaxshi natijalar jamoa oldida e’tirof etiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',6,'Xodimlar qoniqishi o‘lchanadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',7,'Xodimlarning taklif va fikrlari muntazam yig‘iladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',8,'Xodimlar uchun qo‘shimcha imtiyozlar mavjudmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Motivatsiya va rag‘bat',9,'Motivatsiya tizimining samaradorligi tahlil qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',1,'Har bir lavozim uchun o‘sish yo‘li belgilanganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',2,'Har bir lavozim uchun kerakli bilim va ko‘nikmalar ro‘yxati bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',3,'Ichki treninglar rejasi bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',4,'Tashqi treninglarga yuborish mezonlari belgilanganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',5,'Har bir xodim uchun rivojlanish rejasi tuziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',6,'Xodimning rivojlanish rejasi rahbar bilan muntazam ko‘rib chiqiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',7,'Treningdan keyin o‘zlashtirilgan bilim va ko‘nikmalar tekshiriladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',8,'Treningda o‘rganilgan bilimlarning amalda qo‘llanishi nazorat qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Rivojlanish',9,'Ichki zaxira kadrlar bazasi yuritiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',1,'Har bir lavozim uchun KPIlar belgilanganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',2,'Xodimlarning davomati kuzatiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',3,'Xodimlarning ish natijalari muntazam kuzatiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',4,'Mijozlarni saqlab qolish ko‘rsatkichi kuzatiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',5,'Xodimlarning ish jarayoni muntazam kuzatiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',6,'Xodimlarning ishi rahbar tomonidan muntazam baholanadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',7,'Xodimga ish sifati bo‘yicha muntazam fikr-mulohaza beriladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',8,'Kasbiy rivojlantirish yig‘ilishlari o‘tkaziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',9,'Muammoli loyihalar yoki jarayonlar bo‘yicha alohida yig‘ilishlar o‘tkaziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',10,'Ish rejalari va vazifalar bajarilishi nazorat qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',11,'Bajarilgan ish sifati nazorat qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',12,'Ish natijalarini baholash sifati nazorat qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',13,'Mijozlarning shikoyatlari muntazam tahlil qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',14,'Xodimlar uchun malaka oshirish rejasi bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',15,'Bo‘lim KPIlari har oy ko‘rib chiqiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',16,'Xodimlarning ishga kechikishlari hisobga olinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',17,'Ishni bekor qilish yoki bajarilmay qolish holatlari hisobga olinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',18,'Ish natijasi pasayishining sabablari tahlil qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',19,'Kuzatuv yoki auditdan keyin rivojlantirish rejasi tuziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',20,'Yangi ish usullari va standartlar xodimlarga o‘rgatiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',21,'Ish jarayonlari yoki bajarilgan ishlar tahlil qilinadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Boʻlimlar ishlashi',22,'Ish jarayonini boshlash va yakunlash bo‘yicha standartlar bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',1,'Ichki majlislarni o‘tkazish tartibi bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',2,'Haftalik bo‘lim yig‘ilishlari muntazam o‘tkaziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',3,'Oylik natijalarni tahlil qilish yig‘ilishlari o‘tkaziladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',4,'Ichki nizolarni hal qilish tartibi bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',5,'Xodimlarning fikr va takliflari muntazam tinglanadimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',6,'Xodimlar uchun anonim fikr bildirish imkoniyati bormi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',7,'Jamoa ichida muomala va hamkorlik qoidalari belgilanganmi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',8,'Rahbarlar xodimlar bilan ochiq muloqot qiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',9,'Jamoaviy tadbirlar muntazam tashkil etiladimi?',1,false),
  ('ejm','Ishlash va samaradorlik','Ichki aloqa va madaniyat',10,'Kompaniya qadriyatlariga amalda rioya qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',1,'Xodimlar qoniqishi bo‘yicha muntazam so‘rov o‘tkaziladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',2,'Xodimlardan kompaniyani ish beruvchi sifatida tavsiya qilishi haqida so‘raladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',3,'So‘rov natijalari tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',4,'Past baho bergan xodimlarning sabablari o‘rganiladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',5,'So‘rov natijalariga ko‘ra chora-tadbirlar rejasi tuziladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',6,'Xodimlar qoniqishi bo‘limlar kesimida tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',7,'Rahbarlar bo‘yicha qoniqish alohida baholanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',8,'Ish sharoitidan qoniqish o‘lchanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',9,'Maosh va rag‘batlantirish tizimidan qoniqish o‘lchanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Qoniqish va sodiqlik',10,'Rivojlanish va o‘sish imkoniyatlaridan qoniqish o‘lchanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',1,'Xodimlar almashinuvi (turnover) ko‘rsatkichi hisoblanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',2,'Xodimlar almashinuvi bo‘limlar kesimida tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',3,'Sinov muddatida ishdan ketgan xodimlar ulushi hisoblanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',4,'Kuchli xodimlarni ushlab qolish rejasi bormi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',5,'Ishdan ketish xavfi bo‘lgan xodimlar oldindan aniqlanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',6,'Bunday xodimlar bilan rahbar rivojlantirish yoki ushlab qolish suhbati o‘tkazadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',7,'Maoshni qayta ko‘rib chiqish tartibi belgilanganmi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',8,'Ish yuklamasi sabab ishdan ketish holatlari tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',9,'Rahbar bilan bog‘liq sabablar tufayli ishdan ketish holatlari tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Xodimni ushlab qolish',10,'Xodimlarni ushlab qolish bo‘yicha KPI yoki maqsadli ko‘rsatkichlar belgilanganmi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',1,'Ishdan bo‘shash tartibi yozilganmi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',2,'Ketayotgan xodim bilan yakuniy suhbat o‘tkaziladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',3,'Ishdan ketish sababi yozib olinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',4,'Ishdan ketish sabablari muntazam tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',5,'Exit interview davomida xodimdan ishdan ketish sabablari va asosiy omillar (rahbar, jamoa, maosh, ish yuklamasi va boshqalar) bo’yicha fikr olinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',6,'Qayta ishga olinishi mumkin bo‘lgan xodimlar alohida belgilanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',7,'Topshirilishi kerak bo‘lgan jihozlar ro‘yxati bormi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',8,'Xodimning barcha tizimlarga kirish huquqlari va loginlari o‘z vaqtida bekor qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Ishdan chiqish',9,'Ishdan bo‘shash bo‘yicha yakuniy hisobot yuritiladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',1,'Muhim lavozimdagi xodimlar qoniqishi alohida o‘lchanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',2,'Muhim lavozimlar uchun o‘sish yo‘li belgilanganmi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',3,'Kuchli xodimlarni ushlab qolish rejasi bormi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',4,'Ish yuklamasi adolatli taqsimlanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',5,'Xodimlarga ishni samarali bajarish uchun zarur yordam va qo‘llab-quvvatlash beriladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',6,'Kuchli xodimlarning ishdan ketish sabablari tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',7,'Bo‘lim rahbari haqida xodimlarning fikri olinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',8,'Muhim lavozimlar uchun zaxira nomzodlar bazasi yuritiladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',9,'Qayta ishga olish mumkin bo‘lgan xodimlar alohida belgilanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',10,'Muhim lavozimlar bo‘yicha turnover alohida tahlil qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',11,'Kuchli xodimlar bilan rivojlanish suhbatlari muntazam o‘tkaziladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',12,'Zaxira nomzodlar bazasi muntazam yangilanadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',13,'Xodim ishdan ketganda uning vazifalarini topshirish rejasi oldindan tuziladimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',14,'Xodim almashganda ish jarayonining uzluksizligi nazorat qilinadimi?',1,false),
  ('ejm','Ushlab qolish va chiqish','Boʻlim sodiqligi',15,'Xodimning ketishi sabab yo‘qotilgan mijozlar yoki biznes natijalari hisoblanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',1,'Har bir lavozim uchun lavozim yo‘riqnomasi bormi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',2,'Lavozim yo‘riqnomalari muntazam yangilanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',3,'Har bir lavozim uchun sinov muddati maqsadlari belgilanganmi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',4,'Har bir lavozim uchun baholash mezonlari bormi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',5,'Xodimlarning ishga qabul qilingan sanasi yagona bazada saqlanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',6,'Xodimlarning hujjatlari to‘liq saqlanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',7,'Mehnat shartnomalari yagona tartibda yuritiladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',8,'Qo‘shimcha kelishuvlar alohida saqlanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',9,'Ishga qabul qilish tartibi yozilganmi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',10,'Ishdan bo‘shatish tartibi yozilganmi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',11,'Ta’til hujjatlari alohida yuritiladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',12,'Kasallik varaqalari bilan ishlash tartibi bormi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',13,'Xodimlarning shaxsiy ma’lumotlari himoyalanganmi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',14,'HR hujjatlari uchun mas’ul shaxs belgilanganmi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','HR hujjatlari',15,'HR hujjatlari muntazam tekshiriladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',1,'Davomatni hisoblash tizimi bormi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',2,'Davomat bo‘yicha oylik hisobot tayyorlanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',3,'Intizomiy ogohlantirish berish tartibi bormi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',4,'Intizomiy ogohlantirishlar yozma qayd etiladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',5,'Takroriy kechikishlar nazorat qilinadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',6,'Rahbarlar davomat ma’lumotlarini ko‘ra oladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',7,'Davomat va intizom buzilishlari muntazam qayd etilib tahlil qilinadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Davomat va intizom',8,'Intizomiy choralar barcha xodimlarga bir xil tartibda qo‘llanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',1,'Xodimlarning ta’til rejasi oldindan tuziladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',2,'Ta’til olish tartibi yozilganmi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',3,'Ta’tilni tasdiqlovchi mas’ullar aniq belgilanganmi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',4,'Xodim ta’tilga chiqqanda uning vazifalarini vaqtincha taqsimlash rejasi tuziladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',5,'Ish jadvalidagi o‘zgarishlar xodimlarga oldindan xabar qilinadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',6,'Ish yuklamasidagi o‘zgarishlar yozma ravishda tasdiqlanadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',7,'Ish jadvali va HR ma’lumotlari o‘zaro mos yuritiladimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',8,'Ortiqcha ish yuklamasi holatlari tahlil qilinadimi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',9,'Dam olish kunidagi ishlar uchun alohida tartib bormi?',1,false),
  ('ejm','HR boshqaruvi va hujjatlar','Ta’til va ish jadvali',10,'Ish jadvali bilan bog‘liq nizolarni hal qilish tartibi bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',1,'Har bir asosiy jarayon uchun standart ish tartibi (SOP) bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',2,'Har bir asosiy jarayon uchun ish rejasi yoki shabloni bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',3,'Har bir jarayon uchun baholash mezonlari bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',4,'Ish vaqtidan samarali foydalanish baholanadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',5,'Bajarilgan ish sifati baholanadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',6,'Ish sifatini baholash uchun yagona audit yoki kuzatuv varaqasi bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',7,'Ish jarayonlari muntazam tahlil qilinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',8,'Jarayondagi xato va muammolar qayd etiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',9,'Ish sifati past bo‘lsa rivojlantirish rejasi tuziladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',10,'Eng yaxshi amaliyotlar jamoa bilan muntazam ulashiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',11,'Zarur hujjatlar va namunalar bazasi bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',12,'Ish uchun kerakli materiallar va yo‘riqnomalar bazasi bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',13,'Ichki yo‘riqnomalar va materiallar muntazam yangilanadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',14,'Xodimlar kerakli hujjat va materiallarni qayerdan olishni biladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',15,'Ichki standartlar va hujjatlar uchun mas’ul shaxs bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',16,'Ichki standartlar va jarayonlar bo‘yicha yig‘ilishlar o‘tkaziladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',17,'Yangi xodimlar ichki hujjatlar va bilim bazasidan foydalanishni tez o‘zlashtiradimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',18,'Ichki standartlar va jarayonlar biznes ehtiyojlariga mos ravishda yangilanadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',19,'Ichki hujjatlar va materiallar sifati bo‘yicha xodimlarning fikri olinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Ish sifati va metodikasi',20,'Ichki hujjatlar va jarayonlar sifati bo‘yicha mijozlarning fikri hisobga olinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',1,'Asosiy natija ko‘rsatkichlari muntazam kuzatiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',2,'Har bir jamoa, bo‘lim yoki loyiha natijalari tahlil qilinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',3,'Past natija ko‘rsatayotgan xodimlar, jamoalar yoki loyihalar ro‘yxati yuritiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',4,'Past natijalar bo‘yicha rivojlantirish rejasi tuziladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',5,'Mijozlarga ish natijalari yoki bajarilgan xizmat haqida muntazam ma’lumot beriladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',6,'Natijasi pasaygan xodim bilan rahbar tomonidan suhbat o‘tkaziladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',7,'Natija pasayishining sabablari qayd etilib tahlil qilinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',8,'Asosiy ko‘rsatkichlar o‘rtasidagi bog‘liqlik tahlil qilinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',9,'Xodim faoliyati va biznes natijalari o‘rtasidagi bog‘liqlik tahlil qilinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',10,'Eng yuqori natija ko‘rsatayotgan xodimlar yoki jamoalar uchun rivojlantirish rejasi bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',11,'Muhim loyiha yoki maqsadlarga tayyorgarlik jarayoni nazorat qilinadimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',12,'Asosiy natijalar bo‘yicha hisobot rahbariyatga muntazam taqdim etiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',13,'Yuqori natijaga erishgan jamoalarning tajribasi boshqalar bilan ulashiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',14,'Asosiy natijalar bo‘yicha oylik tahlil o‘tkaziladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijoz natijasi bilan ishlash',15,'Natijalar asosida KPIlar muntazam qayta ko‘rib chiqiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',1,'Mijoz bilan ishlovchi xodimlarning vazifalari aniq belgilanganmi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',2,'Mijoz bilan ishlash tartibi yozilganmi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',3,'Mijozning vakili yoki manfaatdor tomonlar bilan ishlash tartibi yozilganmi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',4,'Mijoz bilan aloqa muntazam kuzatiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',5,'Mijozning holati va natijalari muntazam kuzatiladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',6,'Muammoli mijozlar haqida mas’ul shaxslarga o‘z vaqtida xabar beriladimi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',7,'Mijozlarga yuboriladigan standart xabarlar va shablonlar bormi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',8,'Shikoyatlar bilan ishlash uchun mas’ul shaxs belgilanganmi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',9,'Mijoz bilan ishlovchi xodimlar uchun KPIlar belgilanganmi?',1,false),
  ('ejm','Bo‘limlar chuqur auditi','Mijozlar bilan aloqa',10,'Mijoz bilan ishlash sifati muntazam audit qilinadimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',1,'Bo‘lim rahbarlari uchun KPIlar belgilanganmi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',2,'Rahbarlarning jamoani ushlab qolish ko‘rsatkichi kuzatiladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',3,'Rahbarlarning xodimlarni rivojlantirish sifati baholanadimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',4,'Rahbarlarning fikr-mulohaza berish sifati baholanadimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',5,'Rahbarlar uchun boshqaruv bo‘yicha treninglar o‘tkaziladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',6,'Rahbarlar xodimlar bilan muntazam yakka suhbat o‘tkazadimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',7,'Rahbarlar natijasi past xodimlar uchun rivojlantirish rejasi tuzadimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',8,'Rahbarlar bo‘lim natijalari bo‘yicha muntazam hisobot beradimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',9,'Rahbarlar almashinuvi uchun zaxira reja bormi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Rahbarlik sifati',10,'Rahbarlar ish sifati muntazam baholanadimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',1,'Zaxira kadrlar bazasi yuritiladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',2,'Kuchli xodimlar rahbarlik lavozimlariga tayyorlanadimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',3,'Xodimlar uchun lavozim bo‘yicha o‘sish yo‘li belgilanganmi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',4,'Har bir asosiy lavozim uchun keyingi o‘sish bosqichlari aniqmi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',5,'Ichki lavozim o‘sishi amalda qo‘llaniladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',6,'Zaxira kadrlar uchun rivojlanish rejasi tuziladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',7,'Zaxira kadrlar bilan muntazam rivojlanish uchrashuvlari o‘tkaziladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',8,'Bo‘sh lavozimlarga avvalo ichki nomzodlar ko‘rib chiqiladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',9,'Zaxira kadrlar bo‘yicha hisobot yuritiladimi?',1,false),
  ('ejm','Rahbarlik va zaxira kadrlar','Zaxira kadrlar',10,'Zaxira kadrlar muntazam baholanadimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',1,'Xodimlar AI vositalaridan mustaqil foydalana oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',2,'Xodimlar AI uchun aniq va tushunarli topshiriq yoza oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',3,'Xodimlar ma’lumot izlash va tahlil qilishda AI’dan foydalana oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',4,'Xodimlar matn, hujjat va hisobotlarni tayyorlashda AI’dan foydalana oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',5,'Xodimlar jadval va ma’lumotlar bilan ishlashda zamonaviy vositalardan foydalana oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',6,'Xodimlar takroriy vazifalarni AI yoki avtomatlashtirish vositalari yordamida tezlashtira oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',7,'Xodimlar vazifaga mos vositani to‘g‘ri tanlay oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',8,'Xodimlar AI bergan natijani tekshirib, xatolarini aniqlay oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',9,'Xodimlar AI natijasini tayyorligicha ko‘chirmasdan, vazifaga moslashtira oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',10,'Xodimlar maxfiy ma’lumotlarni AI vositalariga kiritmaslik kerakligini biladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',11,'Xodimlar ish uchun kerakli zamonaviy dastur va platformalardan foydalana oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',12,'Xodimlar yangi dastur yoki texnologiyani tez o‘zlashtira oladimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',13,'Zamonaviy vositalardan foydalanish natijasida ish vaqti va sifati yaxshilanayaptimi?',1,false),
  ('ejm','Xodimlar AI va boshqa zamonaviy bilimlarni bilish darajasi','Xodimlar AI''ni bilish darajasi',14,'Xodimlarning bu ko‘nikmalari amaliy topshiriq orqali tekshiriladimi?',1,false)
ON CONFLICT (tur, versiya, bosqich, blok, tartib) DO UPDATE SET
  matn = EXCLUDED.matn, ixtiyoriy = EXCLUDED.ixtiyoriy;
